// Date: 3/24/2014 3:58:00 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package us.teamtinker.armor.armors;

import net.minecraft.client.model.ModelBiped;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SkrawlesHat extends ModelBiped {
	// fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;

	public SkrawlesHat(float f) {
		super(f, 0, 64, 64);

		Shape1 = new ModelRenderer(this, 0, 32);
		Shape1.addBox(-5F, -9F, -5F, 10, 1, 10);
		Shape1.setRotationPoint(0F, 0F, 0F);
		Shape1.setTextureSize(64, 64);
		Shape1.mirror = true;
		setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 43);
		Shape2.addBox(-4F, -11F, -4F, 8, 2, 8);
		Shape2.setRotationPoint(0F, 0F, 0F);
		Shape2.setTextureSize(64, 64);
		Shape2.mirror = true;
		setRotation(Shape2, 0F, 0F, 0F);

		this.bipedHead.addChild(Shape1);
		this.bipedHead.addChild(Shape2);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3,
			float f4, float f5) {
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z) {
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}
}
